# This run in the mattermost gitlab internal instance
variables:
  AWS_DEFAULT_REGION: "us-east-1"

  IMAGE_BUILD: cimg/node:16.2.0
  IMAGE_AWS_CI: $CI_REGISTRY/images/aws-ci:2.1.1-1

stages:
  - build
  - deploy

build-package:
  stage: build
  image: $IMAGE_BUILD
  script:
    - mkdir -p node_modules
    - make build
  artifacts:
    paths:
      - ./v4/html
    expire_in: 2 hours
  only:
    refs:
      - master

s3-release:
  image: $IMAGE_AWS_CI
  stage: deploy
  script:
    - aws s3 cp v4/html s3://api.mattermost.com/ --recursive --cache-control no-cache --acl public-read
    - aws s3 cp v4/html s3://api.mattermost.com/v4/ --recursive --cache-control no-cache --acl public-read
  needs:
    - build-package
  only:
    refs:
      - master
