swagger: '2.0'
info:
  description: >-
    This is the Mattemost API reference.
  version: 3.0.0
  title: Mattermost API Reference
  termsOfService: 'https://about.mattermost.com/default-terms/'
  contact:
    email: feedback@mattermost.com
  x-logo:
    url: "https://www.mattermost.org/wp-content/uploads/2016/03/logoHorizontal_WS.png"
    backgroundColor: "#FFFFFF"
basePath: /api/v3
host: your-mattermost-url.com
tags:
  - name: introduction
    description: Mattermost offers a RESTful Web Service API for interacting with the server. This document acts as a reference for version 3 of that API. For other documentation please see https://docs.mattermost.com.
  - name: schema
    description: All API access is through HTTP(S) requests at `your-mattermost-url.com/api/v3`. All request and response bodies are `application/json`.
  - name: drivers
    description: |
      The easiest way to interact with the Mattermost Web Service API is through a language specific driver. These can be found at the following links:
      
      * [Mattermost JavaScript Driver](https://github.com/mattermost/mattermost-driver-javascript)
      * [Mattermost Golang Driver](https://github.com/mattermost/platform/blob/master/model/client.go)
      
      For an example usage of the Golang driver, please see the [Golang Bot Sample](https://github.com/mattermost/mattermost-bot-sample-golang).
    
  - name: authentication
    description: |
      The majority of the Mattermost API involves interacting with teams. Therefore, most API methods require authentication as a user. There are two ways to authenticate into a Mattermost system.
      
      All examples assume there is a Mattermost instance running at http://localhost:8065.
      
      #### Session Token
      
      Make an HTTP POST to `your-mattermost-url.com/api/v3/users/login` with a JSON body indicating the name of the team, the user’s `login_id`, `password` and optionally the MFA `token`. The `login_id` can be an email, username or an AD/LDAP ID depending on the system's configuration.
      
      ```
      curl -i -d '{"login_id":"someone@nowhere.com","password":"thisisabadpassword"}' http://localhost:8065/api/v3/users/login
      ```
      
      If successful, the response will contain a `Token` header and a user object in the body.
      
      ```
      HTTP/1.1 200 OK
      Set-Cookie: MMSID=hyr5dmb1mbb49c44qmx4whniso; Path=/; Max-Age=2592000; HttpOnly
      Token: hyr5dmb1mbb49c44qmx4whniso
      X-Ratelimit-Limit: 10
      X-Ratelimit-Remaining: 9
      X-Ratelimit-Reset: 1
      X-Request-Id: smda55ckcfy89b6tia58shk5fh
      X-Version-Id: developer
      Date: Fri, 11 Sep 2015 13:21:14 GMT
      Content-Length: 657
      Content-Type: application/json; charset=utf-8
      
      {{user object as json}}
      ```
      
      Include the `Token` as part of the `Authentication` header on your future API requests with the `Bearer` method.
      
      ```
      curl -i -H 'Authorization: Bearer hyr5dmb1mbb49c44qmx4whniso' http://localhost:8065/api/v3/users/me
      ```
      
      You should now be able to access the API as the user you logged in as.
      
      #### OAuth 2.0
      
      Mattermost has the ability to act as an [OAuth 2.0](https://tools.ietf.org/html/rfc6749) service provider.
      
      For an example on how to register an OAuth 2.0 app with your Mattermost instance, please see the [Mattermost-Zapier integration documentation](https://docs.mattermost.com/integrations/zapier.html#register-zapier-as-an-oauth-2-0-application).
      
      Additional documentation on using Mattermost as an OAuth 2.0 service provider will be added here in the future.
  - name: errors
    description: |
      All errors will return an appropriate HTTP response code along with the following JSON body:
      ```
      {
          "id": "the.error.id",
          "message": "Something went wrong", // the reason for the error
          "request_id": "", // the ID of the request
          "status_code": 0, // the HTTP status code
          "is_oauth": false // whether the error is OAuth specific
      }
      ```
  - name: rate limiting
    description: |
      Whenever you make an HTTP request to the Mattermost API you might notice the following headers included in the response:
      ```
      X-Ratelimit-Limit: 10
      X-Ratelimit-Remaining: 9
      X-Ratelimit-Reset: 1441983590
      ```
      
      These headers are telling you your current rate limit status.
      
      | Header | Description |
      | ------ | ----------- |
      | X-Ratelimit-Limit | The maximum number of requests you can make per second. |
      | X-Ratelimit-Remaining | The number of requests remaining in the current window. |
      | X-Ratelimit-Reset | The remaining UTC epoch seconds before the rate limit resets. |
      
      If you exceed your rate limit for a window you will receive the following error in the body of the response:
      
      ```
      HTTP/1.1 429 Too Many Requests
      Date: Tue, 10 Sep 2015 11:20:28 GMT
      X-RateLimit-Limit: 10
      X-RateLimit-Remaining: 0
      X-RateLimit-Reset: 1
      
      limit exceeded
      ```
  - name: users
    description: Anything related to the user data model
  - name: teams
    description: Anything related to the team data model
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/create:
    post:
      tags:
        - users
      summary: Create a new user
      parameters:
        - in: body
          name: body
          description: Abbreviated user object that is to be created
          required: true
          schema:
            type: object
            required:
              - email
              - username
              - password
            properties:
              email:
                type: string
              username:
                type: string
              first_name:
                 type: string
              last_name:
                type: string
              nickname:
                type: string
              password:
                type: string
              locale:
                type: string
              props:
                type: object
      responses:
        '200':
          description: User creation successful
          schema:
            $ref: '#/definitions/User'
            
  /users/me:
    get:
      tags:
        - users
      summary: Get your user object
      description: Returns the user object for the currently logged in user.
      responses:
        '200':
          description: User object retrieval successful
          schema:
            $ref: '#/definitions/User'
  
  /users/login:
    post:
      tags:
        - users
      summary: Login to a user account
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - login_id
              - password
            properties:
              login_id:
                type: string
                description: Username, email, or AD/LDAP ID of a user
              password:
                type: string
                description: User's password
              token:
                type: string
                description: Multi-factor authentication token, if required by the user
              device_id:
                type: string
                description: Mobile device ID, for Android or iOS
              
      responses:
        '200':
          description: User logged in successfuly
          headers:
            token:
              type: string
              description: Access token to be included with future requests
          schema:
            $ref: '#/definitions/User'
  
  /users/logout:
    post:
      tags:
        - users
      summary: Logout of a user account
      responses:
        '200':
          description: User logged out successfuly
          schema:
            properties:
              user_id:
                type: string

  '/users/profiles/{team_id}':
    get:
      tags:
        - users
      summary: Get a list of sanitized user objects by team ID
      parameters:
        - name: team_id
          in: path
          description: Team ID of the users to return
          required: true
          type: string
      responses:
        '200':
          description: Profiles retreived successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
              
  /users/update:
    post:
      tags:
        - users
      summary: Update a user object
      parameters:
        - in: body
          name: body
          description: User object to update with
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: User creation successful
          schema:
            $ref: '#/definitions/User'
            
  /users/update_roles:
    post:
      tags:
        - users
      summary: Update a user's roles
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - user_id
              - roles
            properties:
              user_id:
                type: string
                description: ID of the user to update the roles of
              team_id:
                type: string
                description: ID of the team the user is on
              roles:
                type: string
                description: Space-delimited list of roles to give the user
      responses:
        '200':
          description: User roles updated successful
          schema:
            type: object
            properties:
              user_id:
                type: string
          examples:
            application/json:
              user_id: "string"
  
  /users/update_active:
    post:
      tags:
        - users
      summary: Update whether a user's account is active
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - user_id
              - active
            properties:
              user_id:
                type: string
                description: ID of the user to set active/inactive
              active:
                type: boolean
                description: Use `true` to set the user active, `false` for inactive
      responses:
        '200':
          description: User active status successfully updated
          schema:
            $ref: '#/definitions/User'
  
  /users/update_notify:
    post:
      tags:
        - users
      summary: Update a user's notification properties
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
      responses:
        '200':
          description: User notification properties successfully updated
          schema:
            $ref: '#/definitions/User'
  
  /users/newpassword:
    post:
      tags:
        - users
      summary: Update a user's password
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - user_id
              - current_password
              - new_password
            properties:
              user_id:
                type: string
                description: The ID of the user to change the password for
              current_password:
                type: string
                description: The user's current password
              new_password:
                 type: string
                 description: The user's new password
      responses:
        '200':
          description: User password updated successfully
          schema:
            type: object
            properties:
              user_id:
                type: string
          examples:
            application/json:
              user_id: "string"
  
  /users/send_password_reset:
    post:
      tags:
        - users
      summary: Send a password reset email
      description: Send an email to the user with a link to reset their password. User must use the email/password sign-in method.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - email
            properties:
              email:
                type: string
                description: The email of the user to send the reset link to
      responses:
        '200':
          description: Password reset email sent successfully
          schema:
            type: object
            properties:
              email:
                type: string
          examples:
            application/json:
              email: someone@example.com
            
  /teams/create:
    post:
      tags:
        - teams
      summary: Create a new team
      parameters:
        - in: body
          name: body
          description: Abbreviated team object that is to be created
          required: true
          schema:
            type: object
            required:
              - name
              - display_name
              - type
            properties:
              name:
                type: string
                description: Unique handler for a team, will be present in the team URL
              display_name:
                type: string
                description: Non-unique UI name for the team
              type:
                 type: string
                 description: "`'O'` for open, `'I'` for invite only"
      responses:
        '200':
          description: Team creation successful
          schema:
            $ref: '#/definitions/Team'  
  /teams/all:
    get:
      tags:
        - teams
      summary: Gets all teams which the current user can has access to. If the user is a System Admin, this will be all teams on the server. Otherwise, it will only be the teams of which the user is a member.
      responses:
        '200':
          description: Teams Found
          schema:
            $ref: '#/definitions/TeamMap'  
  '/teams/members/{team_id}':
    get:
      tags:
        - teams
      summary: Get all the members of the specified team.
      parameters:
        - name: team_id
          in: path
          description: Team ID of the members to return
          required: true
          type: string
      responses:
        '200':
          description: Members retreived successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/TeamMember"
  '/teams/{team_id}/me':
    get:
      tags:
        - teams
      summary: Gets the team object
      parameters:
        - name: team_id
          in: path
          description: Team ID of the team you want to retrieve
          required: true
          type: string
      responses:
        '200':
          description: Team object
          schema:
            $ref: "#/definitions/Team"
  '/teams/{team_id}/update':
    post:
      tags:
        - teams
      summary: Update a team object
      parameters:
        - name: team_id
          in: path
          description: Team ID of the team you want to update
          required: true
          type: string
        - in: body
          name: body
          description: Team object to update with
          required: true
          schema:
            $ref: '#/definitions/Team'
      responses:
        '200':
          description: The updated team object
          schema:
            $ref: "#/definitions/Team"
  '/teams/{team_id}/add_user_to_team':
    post:
      tags:
        - teams
      summary: Add a user to a team.
      parameters:
        - name: team_id
          in: path
          description: Team ID of the team you want to add the user too
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - user_id
            properties:
              user_id:
                type: string
                description: The user_id of the user to add to the team.
      responses:
        '200':
          description: User added sucessfully
  '/teams/{team_id}/remove_user_from_team':
    post:
      tags:
        - teams
      summary: Remove a user from a team.
      parameters:
        - name: team_id
          in: path
          description: Team ID of the team you want to remove the user from
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - user_id
            properties:
              user_id:
                type: string
                description: The user_id of the user to remove from the team.
      responses:
        '200':
          description: User removed sucessfully
            
definitions:
  User:
    type: object
    properties:
      id:
        type: string
      create_at:
        type: integer
      update_at:
        type: integer
      delete_at:
        type: integer
      username:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      nickname:
        type: string
      email:
        type: string
      email_verified:
        type: boolean
      password:
        type: string
      auth_data:
        type: string
      auth_service:
        type: string
      roles:
        type: string
      locale:
        type: string
      notify_props:
        type: object
      props:
        type: object
      last_password_update:
        type: integer
      last_picture_update:
        type: integer
      failed_attempts:
        type: integer
      mfa_active:
        type: boolean
      mfa_secret:
        type: string
        
  Team:
    type: object
    properties:
      id:
        type: string
      create_at:
        type: integer
      update_at:
        type: integer
      delete_at:
        type: integer
      display_name:
        type: string
      name:
        type: string
      email:
        type: string
      type:
        type: string
      allowed_domains:
        type: string
      invite_id:
        type: string
      allow_open_invite:
        type: boolean
        
  TeamMap:
    type: object
    description: A mapping of teamIds to teams.
    properties:
      team_id:
        $ref: '#/definitions/Team'
        
  TeamMember:
    type: object
    properties:
      team_id:
        type: string
      user_id:
        type: string
      roles:
        type: string
      
externalDocs:
  description: Find out more about Mattermost
  url: 'https://about.mattermost.com'
